local function write_fp_wrapper(path, target, php_shim)
    local utils = require("utils")
    local f, err = io.open(path, "w")
    if not f then error("Cannot write wrapper " .. path .. ": " .. (err or "unknown error")) end
    f:write("#!/usr/bin/env bash\n")
    -- PHPX_FRANKENPHP_VERSION is injected by phpx:phpx BackendExecEnv at runtime
    f:write(utils.FP_FN .. "\n")
    f:write('_FP_BIN=$(fp_path "${PHPX_FRANKENPHP_VERSION:-latest}") || exit 127\n')
    -- Inject PHP_INI_SCAN_DIR pointing to ini-scan/ which has a symlink to the active ini
    f:write('export PHP_INI_SCAN_DIR="${MISE_DATA_DIR:-$HOME/.local/share/mise}/phpx/ini-scan"\n')
    if php_shim then
        -- PHP_BINARY is "" under FrankenPHP, so tools that re-exec PHP (PHPStan's
        -- TurboProcessRestarter via pcntl_exec, symfony/process PhpExecutableFinder,
        -- `#!/usr/bin/env php` launchers) end up running whatever `php` is on PATH.
        -- Put our FrankenPHP shim first on PATH (shared libexec, see write_php_shim)
        -- and advertise it through the env vars those tools consult, so subprocesses
        -- never fall back to a system PHP.
        local shim_dir = php_shim:match("^(.*)/[^/]+$")
        f:write('export PATH=' .. shim_dir .. ':"$PATH"\n')
        f:write('export PHP_BINARY=' .. php_shim .. ' PHP_PATH=' .. php_shim .. '\n')
    end
    f:write('exec "$_FP_BIN" php-cli ' .. target .. ' "$@"\n')
    f:close()
    os.execute("chmod +x " .. path)
end

-- Writes a `php` shim backed by FrankenPHP. FrankenPHP's php-cli only takes a
-- script (or -r code) and its arguments, so the php flags tools commonly pass
-- (-c, -d, -n) are translated into a temporary PHP_INI_SCAN_DIR that also carries
-- the plugin-managed extensions ini.
-- The shim lives in <MISE_DATA_DIR>/phpx/libexec (shared by every tool): mise
-- strips any PATH entry under its installs/ directory when it re-computes PATH
-- for a nested `mise x`, so a per-install libexec/ would never reach subprocesses.
local function write_php_shim(path)
    local f, err = io.open(path, "w")
    if not f then error("Cannot write PHP shim " .. path .. ": " .. (err or "unknown error")) end
    local utils = require("utils")
    -- (gsub returns a second value; the extra parentheses keep only the string)
    f:write((([=[#!/usr/bin/env bash
# php shim generated by mise-phpx: runs FrankenPHP's php-cli, emulating php's -c/-d/-n flags.
__FP_FN__
_FP_BIN=$(fp_path "${PHPX_FRANKENPHP_VERSION:-latest}") || exit 127
_FP="$_FP_BIN php-cli"
_SCAN_SRC="${PHP_INI_SCAN_DIR:-${MISE_DATA_DIR:-$HOME/.local/share/mise}/phpx/ini-scan}"
_TMP=$(mktemp -d "${TMPDIR:-/tmp}/phpx-ini-XXXXXX") || exit 1
_cleanup() { rm -rf "$_TMP"; }
trap _cleanup EXIT
if [[ -d "$_SCAN_SRC" ]]; then cp -L "$_SCAN_SRC"/*.ini "$_TMP"/ 2>/dev/null || true; fi
_add_ini() { local kv="$1"; [[ "$kv" == *=* ]] || kv="${kv}=1"; printf '%s\n' "$kv" >> "$_TMP/zz-overrides.ini"; }
_add_file() { if [[ -d "$1" ]]; then [[ -f "$1/php.ini" ]] && cp "$1/php.ini" "$_TMP/00-php.ini"; elif [[ -f "$1" ]]; then cp "$1" "$_TMP/00-php.ini"; fi; }
_parse_flags() {
    # Consumes leading php flags from "$@" into _REST (flags applied as side effects).
    _REST=()
    while [[ $# -gt 0 ]]; do
        case "$1" in
            -d)  _add_ini "$2"; shift 2 ;;
            -d*) _add_ini "${1#-d}"; shift ;;
            -c)  _add_file "$2"; shift 2 ;;
            -c*) _add_file "${1#-c}"; shift ;;
            -n|-q|-H) shift ;;
            *) break ;;
        esac
    done
    _REST=("$@")
}
# PHP_BINARY is "" under FrankenPHP. When a tool re-execs itself through
# pcntl_exec(PHP_BINARY, [flags..., argv...]) the kernel falls back to the script's
# `#!/usr/bin/env php` shebang and we are called as: php <script> <flags...> <script> <args...>
# Recognise that shape (same script path twice with only php flags in between) and
# fold it back into: php <flags...> <script> <args...>.
if [[ $# -ge 2 && -f "$1" && "$2" == -* ]]; then
    _script="$1"; shift
    _saved=("$@")
    _parse_flags "$@"
    if [[ ${#_REST[@]} -gt 0 && "${_REST[0]}" == "$_script" ]]; then
        set -- "${_REST[@]}"
    else
        rm -f "$_TMP/zz-overrides.ini" "$_TMP/00-php.ini"
        set -- "$_script" "${_saved[@]}"
    fi
fi
while [[ $# -gt 0 ]]; do
    case "$1" in
        -d)  _add_ini "$2"; shift 2 ;;
        -d*) _add_ini "${1#-d}"; shift ;;
        -c)  _add_file "$2"; shift 2 ;;
        -c*) _add_file "${1#-c}"; shift ;;
        -n|-q|-H) shift ;;
        -v|--version)
            PHP_INI_SCAN_DIR="$_TMP" $_FP -r 'echo "PHP ".PHP_VERSION." (cli) (FrankenPHP)".PHP_EOL;'; exit $? ;;
        -m|--modules)
            PHP_INI_SCAN_DIR="$_TMP" $_FP -r 'echo "[PHP Modules]".PHP_EOL; foreach (get_loaded_extensions() as $e) echo $e, PHP_EOL;'; exit $? ;;
        --ini)
            PHP_INI_SCAN_DIR="$_TMP" $_FP -r 'echo "Loaded Configuration File: ".(php_ini_loaded_file() ?: "(none)").PHP_EOL."Scan for additional .ini files in: ".getenv("PHP_INI_SCAN_DIR").PHP_EOL;'; exit $? ;;
        --) shift; break ;;
        *) break ;;
    esac
done
PHP_INI_SCAN_DIR="$_TMP" $_FP "$@"
]=]):gsub("__FP_FN__", function() return utils.FP_FN end)))
    f:close()
    os.execute("chmod +x " .. path)
end

function PLUGIN:BackendInstall(ctx)
    local utils = require("utils")
    local backend = utils.detect_backend(ctx)
    local tool    = utils.get_tool(ctx)

    if backend == "phpx" then
        -- Pre-install FrankenPHP at the pinned version so it's ready at runtime.
        -- Uses github:php/frankenphp to support all versions (incl. pre-1.3.0).
        local cmd = require("cmd")
        local a   = require("aliases")
        local fp_version = a.resolve_phpx(ctx.version)
        local ok, out = pcall(function()
            return cmd.exec(utils.fp_bin_expr(fp_version) .. " --version 2>&1")
        end)
        if not ok then
            error("Failed to install FrankenPHP " .. fp_version .. ":\n" .. tostring(out))
        end

        -- Expose the phpx wrapper on PATH: mise adds <install_path>/bin automatically,
        -- so link the plugin's bin/phpx there (BackendExecEnv has no exec_path concept).
        local plugin_dir = utils.plugin_dir(ctx)
        if plugin_dir then
            os.execute("mkdir -p " .. utils.shell_quote(ctx.install_path .. "/bin"))
            os.execute("ln -sf " .. utils.shell_quote(plugin_dir .. "/bin/phpx") .. " "
                .. utils.shell_quote(ctx.install_path .. "/bin/phpx"))
        end
        -- Also provide a `php` command backed by FrankenPHP (shared shim, see
        -- write_php_shim) so scripts, shebangs and tools find a PHP without a system one.
        local php_shim = utils.data_dir() .. "/libexec/php"
        os.execute("mkdir -p " .. utils.shell_quote(utils.data_dir() .. "/libexec")
            .. " " .. utils.shell_quote(ctx.install_path .. "/bin"))
        write_php_shim(php_shim)
        os.execute("ln -sf " .. utils.shell_quote(php_shim) .. " " .. utils.shell_quote(ctx.install_path .. "/bin/php"))

        -- extensions = "mongodb/mongodb-extension microsoft/pdo_sqlsrv" (or a TOML array)
        -- Compiles/installs each PIE package via `phpx -x install` so extensions are
        -- provisioned declaratively from mise.toml, pinned to this FrankenPHP version.
        local extensions = utils.opt_list(ctx.options and ctx.options.extensions)
        if #extensions > 0 then
            if not plugin_dir then
                error("Cannot locate plugin directory to run `phpx -x install`")
            end
            local phpx_bin = plugin_dir .. "/bin/phpx"
            for _, ext in ipairs(extensions) do
                local ok, out = pcall(function()
                    return cmd.exec("PHPX_FRANKENPHP_VERSION=" .. utils.shell_quote(fp_version)
                        .. " " .. utils.shell_quote(phpx_bin) .. " -x install " .. utils.shell_quote(ext) .. " 2>&1")
                end)
                if not ok then
                    error("Failed to install PHP extension " .. ext .. ":\n" .. tostring(out))
                end
            end
        end
        return {}

    elseif backend == "composer" then
        local cmd = require("cmd")
        local a   = require("aliases")
        local package = a.resolve_composer(tool)

        local q    = utils.shell_quote
        local opts = ctx.options or {}

        os.execute("mkdir -p " .. ctx.install_path)
        local phar = utils.ensure_composer_phar(cmd)
        local composer_json = ctx.install_path .. "/composer.json"

        -- COMPOSER_ALLOW_SUPERUSER: Composer silently disables plugins (e.g.
        -- phpstan/extension-installer) when running as root, as in CI containers.
        local function composer(args)
            return "COMPOSER_ALLOW_SUPERUSER=1 " .. utils.FP .. " " .. phar .. " " .. args
                .. " --working-dir=" .. q(ctx.install_path) .. " --no-interaction"
        end

        -- composer_json = "path/to/composer.json": seed the install project with a
        -- user-provided manifest (require-dev, config.allow-plugins, repositories, ...).
        -- Relative paths resolve against the mise project root, then the current dir.
        if opts.composer_json and opts.composer_json ~= "" then
            local src = tostring(opts.composer_json)
            if not src:match("^/") then
                local root = os.getenv("MISE_PROJECT_ROOT") or os.getenv("PWD") or "."
                src = root .. "/" .. src
            end
            local f = io.open(src, "r")
            if not f then error("composer_json file not found: " .. src) end
            f:close()
            cmd.exec("cp " .. q(src) .. " " .. q(composer_json))
        end

        -- `composer config` refuses to run without a composer.json; start from an empty one.
        local f = io.open(composer_json, "r")
        if f then f:close() else
            f = io.open(composer_json, "w")
            if f then f:write("{}\n") f:close() end
        end

        -- allow_plugins = "phpstan/extension-installer" (or "true" to allow every plugin)
        for _, plugin in ipairs(utils.opt_list(opts.allow_plugins)) do
            if plugin == "true" or plugin == "*" then
                cmd.exec(composer("config allow-plugins true"))
            else
                cmd.exec(composer("config " .. q("allow-plugins." .. plugin) .. " true"))
            end
        end

        -- config = "process-timeout=600 platform.php=8.3" → composer config <key> <value>
        for _, kv in ipairs(utils.opt_list(opts.config)) do
            local key, value = kv:match("^([^=]+)=(.*)$")
            if not key then
                error("Invalid composer config entry '" .. kv .. "' (expected key=value)")
            end
            cmd.exec(composer("config " .. q(key) .. " " .. q(value)))
        end

        -- extra = "phpstan/phpstan-strict-rules:^2.0 phpstan/extension-installer"
        -- Extra packages are required together with the main one so Composer solves
        -- all constraints at once. A package without constraint lets Composer pick.
        local specs = { q(package .. ":" .. ctx.version) }
        for _, extra in ipairs(utils.opt_list(opts.extra)) do
            specs[#specs + 1] = q(extra)
        end

        -- cmd.exec raises on non-zero exit and drops the output, so capture it
        -- ourselves and detect failure through a marker to report Composer's message.
        local result = cmd.exec(composer("require " .. table.concat(specs, " "))
            .. " 2>&1 || echo __PHPX_COMPOSER_FAILED__") or ""
        if result:match("__PHPX_COMPOSER_FAILED__") then
            error("Failed to install " .. package .. "@" .. ctx.version .. ":\n"
                .. (result:gsub("__PHPX_COMPOSER_FAILED__%s*$", "")))
        end

        local pkg_dir = ctx.install_path .. "/vendor/" .. package
        pcall(function()
            cmd.exec(utils.FP .. " " .. phar
                .. " install --working-dir=" .. pkg_dir .. " --no-interaction --quiet")
        end)

        -- Inject version into vendor package composer.json (Composer strips it at install).
        -- Needed by tools like cpx that read __DIR__/../../composer.json for their version.
        local pkg_json = pkg_dir .. "/composer.json"
        local clean_version = ctx.version:gsub("^v", "")
        pcall(function()
            cmd.exec("python3 -c \"" ..
                "import json; p='" .. pkg_json .. "'; " ..
                "d=json.load(open(p)); d.setdefault('version','" .. clean_version .. "'); " ..
                "open(p,'w').write(json.dumps(d,indent=2))\"")
        end)

        -- PHP shim for subprocesses spawned by the tools (see write_php_shim)
        local php_shim = utils.data_dir() .. "/libexec/php"
        os.execute("mkdir -p " .. q(utils.data_dir() .. "/libexec"))
        write_php_shim(php_shim)

        -- Create FrankenPHP wrappers for each vendor/bin script
        local bin_dir = ctx.install_path .. "/bin"
        os.execute("mkdir -p " .. bin_dir)
        local bins = cmd.exec("ls " .. ctx.install_path .. "/vendor/bin/ 2>/dev/null") or ""
        for binary in bins:gmatch("[^\n]+") do
            if binary ~= "" then
                local src  = ctx.install_path .. "/vendor/bin/" .. binary
                local dest = bin_dir .. "/" .. binary
                write_fp_wrapper(dest, src, php_shim)
            end
        end

        return {}

    elseif backend == "phive" then
        local cmd  = require("cmd")
        local json = require("json")
        local a    = require("aliases")
        local resolved = a.resolve_phive(tool)
        
        -- resolved can be a string (vendor/repo) or table (config with repo, options)
        local repo, config
        if type(resolved) == "table" then
            repo = resolved.repo
            config = resolved
        else
            repo = resolved
            config = {}
        end

        if not repo:match("/") then
            error("PHAR tool must be vendor/repo format or a known alias")
        end

        cmd.exec("mkdir -p " .. ctx.install_path)
        local phar_name = repo:match("([^/]+)$")

        -- Use GitHub API to find the actual PHAR asset URL.
        -- version_prefix controls how ctx.version maps to a release tag.
        -- When nil, probe "v{version}" then bare version (safe default for unknown repos).
        local token   = os.getenv("GITHUB_TOKEN") or os.getenv("GH_TOKEN")
        local auth    = token and (" -H 'Authorization: Bearer " .. token .. "'") or ""
        local version_prefix = (ctx.options and ctx.options.version_prefix) or config.version_prefix
        local tags_to_try = version_prefix ~= nil
            and { version_prefix .. ctx.version }
            or  { "v" .. ctx.version, ctx.version }
        local api_ok, api_out, tag_used
        for _, tag in ipairs(tags_to_try) do
            local api_url = "https://api.github.com/repos/" .. repo .. "/releases/tags/" .. tag
            local ok, out = pcall(function()
                return cmd.exec("curl -sL" .. auth .. " '" .. api_url .. "'")
            end)
            if ok and out and out ~= "" then
                local probe = json.decode(out) or {}
                if probe.assets then
                    api_ok, api_out, tag_used = ok, out, tag
                    break
                end
            end
        end
        if not tag_used then tag_used = (version_prefix or "v") .. ctx.version end
        local phar_url  = nil
        local phar_file = nil
        if api_ok and api_out and api_out ~= "" then
            local data = json.decode(api_out) or {}
            if data.assets then
                -- Get options from config and ctx.options (ctx.options take precedence)
                local matching = (ctx.options and ctx.options.matching) or config.matching
                local matching_regex = (ctx.options and ctx.options.matching_regex) or config.matching_regex
                local asset_pattern = (ctx.options and ctx.options.asset_pattern) or config.asset_pattern
                
                -- asset_pattern takes precedence: direct pattern match
                if asset_pattern then
                    for _, asset in ipairs(data.assets) do
                        local name = asset.name or ""
                        -- Simple glob-like pattern matching (* becomes .*)
                        local pattern = asset_pattern:gsub(".", {
                            ["*"] = ".*", ["."] = "%.", ["-"] = "%-",
                            ["+"] = "%%+", ["?"] = "%?"
                        })
                        if name:match("^" .. pattern .. "$") then
                            phar_url  = asset.browser_download_url
                            phar_file = name
                            break
                        end
                    end
                else
                    -- Collect candidates filtered by matching/matching_regex
                    local candidates = {}
                    for _, asset in ipairs(data.assets) do
                        local name = asset.name or ""
                        if name:match("%.phar$") and not name:match("%.asc$") and not name:match("%.sha") then
                            local matches = true
                            if matching and not name:find(matching, 1, true) then
                                matches = false
                            end
                            if matches and matching_regex then
                                local ok, result = pcall(function() return name:match(matching_regex) end)
                                if not ok or not result then matches = false end
                            end
                            if matches then
                                table.insert(candidates, asset)
                            end
                        end
                    end
                    -- Prefer the phar whose name matches the repo name (e.g. php-toolkit.phar
                    -- over blueprints.phar when repo is WordPress/php-toolkit).
                    -- Fall back to the first candidate when no name match is found.
                    local picked = candidates[1]
                    if not matching and not matching_regex then
                        for _, asset in ipairs(candidates) do
                            if (asset.name or ""):match("^" .. phar_name:gsub("%-", "%%-") .. "%.phar$") then
                                picked = asset
                                break
                            end
                        end
                    end
                    if picked then
                        phar_url  = picked.browser_download_url
                        phar_file = picked.name
                    end
                end
            end
        end

        if not phar_url then
            phar_file = phar_name .. ".phar"
            phar_url  = "https://github.com/" .. repo .. "/releases/download/" .. tag_used .. "/" .. phar_file
        end

        local phar_path = ctx.install_path .. "/" .. phar_file
        cmd.exec("curl -sL -o " .. phar_path .. " " .. phar_url)

        local _, stat = pcall(function() return cmd.exec("test -s " .. phar_path .. " && echo ok") end)
        if not (stat and stat:match("ok")) then
            error("Failed to download " .. phar_file .. " from " .. phar_url)
        end

        cmd.exec("chmod +x " .. phar_path)
        
        -- Determine the executable name: rename_exe > bin > tool alias > phar_name
        local rename_exe = (ctx.options and ctx.options.rename_exe) or config.rename_exe
        local bin_config = (ctx.options and ctx.options.bin) or config.bin
        local exe_name = rename_exe or bin_config or tool or phar_name

        -- PHP shim for subprocesses spawned by the PHAR (see write_php_shim)
        local php_shim = utils.data_dir() .. "/libexec/php"
        os.execute("mkdir -p " .. utils.shell_quote(utils.data_dir() .. "/libexec"))
        write_php_shim(php_shim)

        -- Create a FrankenPHP wrapper, pointing PHP_BINARY to the shim
        write_fp_wrapper(ctx.install_path .. "/" .. exe_name, phar_path, php_shim)

        return {}

    else
        error("Unknown backend: " .. backend)
    end
end
